version: '3'
services:
    backend:
      container_name: backend
      restart: always
      build: ./backend/
      volumes:
        - ./logs:/winston_logs
      ports:
        - "8000:8000"
        - "8001:8001"
      links:
        - mongo
        - redis

    mongo:
      container_name: database
      image: mongo
      volumes:
        - ./data:/data/db
      ports:
        - "127.0.0.1:27017:27017"

    redis:
      container_name: redis
      image: "redis:alpine"
      command: redis-server --requirepass XSS_bomb_RedisPass321@!
      volumes:
        - ./redis:/data
      ports:
        - "127.0.0.1:6379:6379"

    admin_panel:
      container_name: admin_panel
      restart: always
      image: mongo-express
      ports:
        - "127.0.0.1:8081:8081"
      environment:
        ME_CONFIG_BASICAUTH_USERNAME: root
        ME_CONFIG_BASICAUTH_PASSWORD: toor
        ME_CONFIG_OPTIONS_EDITORTHEME: material
      links:
        - mongo
